version: '3.8'

services:
  app:
    image: myspringrest-app:1.1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "8888:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5555/myspringrest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3gor
    depends_on:
      - postgres
  postgres:
    image: postgres:16.4
    container_name: postgres_db
    environment:
      POSTGRES_DB: myspringrest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3gor
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: