spring:
  application:
    name: MySpringREST
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
  datasource:
    password: 3gor
    url: jdbc:postgresql://host.docker.internal:5555/myspringrest
    driver-class-name: org.postgresql.Driver
    username: postgres
  liquibase:
    change-log: classpath:db/changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8080
app:
  url:
    base: /api/v1
    people: ${app.url.base}/people
    messages: ${app.url.base}/messages
    admin: ${app.url.people}/admin
  secret: golovkov